### ISSUE TITLE
SNMP Notifier "Error":true,"Status":422

### ISSUE THREAD

**Issue by mencutekin** [maxwo/snmp_notifier#133]
**What did you do?**

SNMP Notifier doesnt get alert from alertmanager. I cannto see anything when I click on SNMP alerts endpoint link in the SNMP Notifier URL.
I can just see this :
{"Error":true,"Status":422,"Message":"EOF"}

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* SNMP notifier version:

	insert output of `snmp_notifier --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager command line:
```
route:
  receiver: "default"
  routes:
   - match:
      severity: critical
     receiver: snmp_notifier
   - match:
      severity: warning
     receiver: email
     group_wait: 30s
     group_interval: 15m
     repeat_interval: 15m
receivers:
  - name: default
    email_configs:
     - to: 'fatih@xxx.com'
       from: 'postgres_alerts@xxx.com'
       smarthost: 'localhost:25'
  - name: snmp_notifier
    webhook_configs:
    - send_resolved: true
      url: http://berlin01:9464/alerts
  - name: email
    email_configs:
     - to: 'fatih@xxx.com'
       from: 'postgres_alerts@xxx.com'
       smarthost: 'localhost:25'
```

* SNMP notifier command line:
```
./snmp_notifier 

```
* Prometheus alert file:

  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: PostgreSQLInstanceUpDown
    expr: pg_up == 0 or up{instance=~".*"} == 0
    for: 1m
    labels:
      severity: critical
      oid: "1.3.6.1.4.1.123.0.10.1.1.1.5.1"
      type: "service"
      environment: "production"
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

* Logs:
```
insert logs relevant to the issue here
```
